### PR TITLE
Adding the refreshing info

### PR DESCRIPTION
**Pull request by feddelegrand7**
Hi Hadley,

Amazing book ! thank you for making it open source. I'm not sure if it's useful but I've added a quick (according to me important) note that inform the user that it's not necessary to quit (CTRL + C) the shiny app and rerun it to preview the modifications. A simple refresh does the trick. 

Best.
Fodil.

### CODE REVIEW

**Comment by hadley** [comment]
I don't think that's true in general?

**Comment by feddelegrand7** [comment]
Mmmm I've tested it in RStudio and VSCode and it's working. In VSCode you need to refresh the web page.

**Comment by hadley** [comment]
Huh, must be an RStudio feature I didn't know about. Let me look into so I can better understand how it works.

**Comment by feddelegrand7** [comment]
Sure :)

**Comment by hadley** [comment]
I took a slightly different approach in 1a9073fbf81172654d5105b2a25555d62d1444a9 — thanks for pointing this out!

**Comment by feddelegrand7** [comment]
You're welcome, I learned that when I was trying to learn Flask ^^

**Pull request closed without merging**
